[tool.poetry]
name = "library"
version = "0.1.0"
description = "Library sample"
authors = ["Andrii Puziuk <frayandy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
